-- V3: append-only audit log (Spec 12, 12.1, 15) and the runtime role's grants.
--
-- Decisions: CLAUDE.md, "B0-6 decisions".
--
-- PRECONDITION: the runtime role (Flyway placeholder `runtime_role`, environment variable
-- PEOPLEHUB_DB_RUNTIME_ROLE, default peoplehub_app) must already exist. Migrations never create roles: CREATE ROLE needs
-- elevated privileges, so roles are provisioned by infrastructure (README, "Database roles"). The first block fails
-- the migration with a readable message if the role is missing or the name is not a plain lower-case identifier.
--
-- The placeholder is only ever used as a string value, and every use in a statement goes through format('%I'), so it is
-- quoted as an identifier. Before Flyway runs at all, RuntimeRolePlaceholderGuard has already refused any value outside
-- the identifier pattern, so nothing but a plain name can reach this file. The check below is the second line of
-- defence, not the first.
DO $mig$
DECLARE
    runtime_role text := '${runtime_role}';
BEGIN
    IF runtime_role !~ '^[a-z_][a-z0-9_]{0,62}$' THEN
        RAISE EXCEPTION 'Flyway placeholder runtime_role is not a valid role name';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = runtime_role) THEN
        RAISE EXCEPTION 'Runtime role "%" does not exist. Provision the database roles before migrating (README, Database roles).',
            runtime_role;
    END IF;
END
$mig$;

-- organization_id is NOT NULL and has no foreign key: the organization table arrives with B2 (b2-1), which adds the FK
-- and the tenant row-level security. Until then nothing may write a row without a real organization id; the writer
-- refuses null and the nil UUID, and no placeholder value is ever inserted to satisfy NOT NULL.
--
-- id and occurred_at are generated by the database only (identity ALWAYS; the runtime role has no INSERT privilege on
-- either column, see below). now() is the transaction start time: rows written in one transaction share occurred_at and
-- id orders them.
--
-- The formats below mirror ActorId (actor_id), CorrelationId (correlation_id) and the audit contract (AuditDetails), so
-- a row written by any path, not only the Java writer, has the same shape. AuditLogMigrationTest keeps them in step.
CREATE TABLE audit_log (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    organization_id UUID         NOT NULL,
    actor_id        VARCHAR(64)  NOT NULL,
    action          VARCHAR(64)  NOT NULL,
    target_type     VARCHAR(64),
    target_id       VARCHAR(64),
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ip              INET,
    correlation_id  VARCHAR(64),
    details         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_audit_log PRIMARY KEY (id),
    CONSTRAINT ck_audit_log_organization_not_nil
        CHECK (organization_id <> '00000000-0000-0000-0000-000000000000'),
    CONSTRAINT ck_audit_log_actor_id
        CHECK (actor_id ~ '^[A-Za-z0-9._:-]{1,64}$'),
    CONSTRAINT ck_audit_log_action
        CHECK (action ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_audit_log_target_type
        CHECK (target_type IS NULL OR target_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_audit_log_target_id
        CHECK (target_id IS NULL OR (target_type IS NOT NULL AND target_id ~ '^[A-Za-z0-9._:-]{1,64}$')),
    CONSTRAINT ck_audit_log_correlation_id
        CHECK (correlation_id IS NULL OR correlation_id ~ '^[A-Za-z0-9._-]{1,64}$'),
    CONSTRAINT ck_audit_log_details
        CHECK (jsonb_typeof(details) = 'object' AND octet_length(details::text) <= 4096)
);

COMMENT ON TABLE audit_log IS 'Append-only audit trail (Spec 12, 15). Rows are only ever inserted; see trg_audit_log_append_only.';
COMMENT ON COLUMN audit_log.organization_id IS 'Tenant of the event. No FK until B2 creates the organization table.';
COMMENT ON COLUMN audit_log.actor_id IS 'ActorId contract: an employee id, anonymous, SYSTEM or job:<name>. Never a name or email.';
COMMENT ON COLUMN audit_log.occurred_at IS 'Database time (now()); the application never supplies it.';
COMMENT ON COLUMN audit_log.details IS 'Versioned structured metadata {"v":1,"attributes":{},"changes":[]}; see AuditDetails. No secrets, no free text.';

-- Append-only, enforced in the database. Defence in depth, together with the runtime role's grants below:
--  * one statement-level trigger rejects UPDATE, DELETE and TRUNCATE (statement level so it fires even when zero rows
--    match, and because TRUNCATE has no row-level trigger). The message carries no row data.
--  * ENABLE ALWAYS keeps it firing under session_replication_role = replica, which would otherwise skip it.
-- Trust boundary (accepted): the table owner or a superuser can still disable or drop this trigger. b0-6 does not try to
-- defend against a malicious database administrator.
CREATE FUNCTION audit_log_reject_change() RETURNS trigger
    LANGUAGE plpgsql
AS $fn$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP;
END
$fn$;

CREATE TRIGGER trg_audit_log_append_only
    BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_log
    FOR EACH STATEMENT
    EXECUTE FUNCTION audit_log_reject_change();

ALTER TABLE audit_log ENABLE ALWAYS TRIGGER trg_audit_log_append_only;

-- Runtime role privileges. The role gets exactly what the application needs and nothing else:
--  * audit_log: SELECT (the future Super Admin viewer reads it) and INSERT on the eight columns the writer supplies.
--    No INSERT on id or occurred_at (both are database-generated), and never UPDATE, DELETE or TRUNCATE.
--  * shedlock (V2): SELECT, INSERT, UPDATE. ShedLock updates and inserts lock rows; PostgreSQL also needs SELECT for
--    the WHERE clause of an UPDATE. It never deletes.
-- No ALTER DEFAULT PRIVILEGES: every migration grants the runtime role table by table, so a new table can never hand it
-- UPDATE or DELETE by accident.
REVOKE ALL ON audit_log FROM PUBLIC;

DO $mig$
DECLARE
    runtime_role text := '${runtime_role}';
BEGIN
    EXECUTE format('GRANT SELECT ON audit_log TO %I', runtime_role);
    EXECUTE format(
        'GRANT INSERT (organization_id, actor_id, action, target_type, target_id, ip, correlation_id, details) '
        'ON audit_log TO %I', runtime_role);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE ON shedlock TO %I', runtime_role);
END
$mig$;
