-- V4: transactional email outbox foundation (Spec 9.2, 12), b1-1.
--
-- Decisions: PROJECT_MASTER_SPEC.md Section 9.2 (transactional outbox), Section 12 (email_outbox /
-- email_send_log). CLAUDE.md B1 planning: one table serves as both the queue and the send history
-- (status transitions ARE the log; no separate email_send_log table). Sending, retry/backoff and
-- templates are b1-2 (this migration creates the full shared shape but only b1-1's narrow slice of
-- privileges); this migration and EmailOutboxWriter only ever produce PENDING rows.
--
-- PRECONDITION: identical guard to V3 -- the runtime role must already exist. Migrations never
-- create roles.
DO $mig$
DECLARE
    runtime_role text := '${runtime_role}';
BEGIN
    IF runtime_role !~ '^[a-z_][a-z0-9_]{0,62}$' THEN
        RAISE EXCEPTION 'Flyway placeholder runtime_role is not a valid role name';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = runtime_role) THEN
        RAISE EXCEPTION 'Runtime role "%" does not exist. Provision the database roles before migrating (README, Database roles).',
            runtime_role;
    END IF;
END
$mig$;

-- organization_id is NOT NULL and has no foreign key, for the same reason as audit_log.organization_id
-- (V3): the organization table arrives with B2 (b2-1), which adds the FK and tenant row-level
-- security. Until then nothing may write a row without a real organization id; EmailOutboxWriter
-- refuses null and the nil UUID, and no placeholder value is ever inserted to satisfy NOT NULL.
--
-- There is no employee table until B2 either, so this table carries no employee reference at all: the
-- spec's own data model (Section 12) only ever gives email_outbox a recipient address, not an employee
-- id.
--
-- id and created_at are generated by the database only (identity ALWAYS; the runtime role has no
-- INSERT privilege on either column, see below).
--
-- Unlike audit_log, this table is deliberately mutable: an outbox is a queue whose rows change status
-- as they are processed (b1-2), so it does NOT get the append-only trigger from V3. That trigger
-- protects an immutable history; applying it here would be a misapplication, not a reuse.
CREATE TABLE email_outbox (
    id                  BIGINT       GENERATED ALWAYS AS IDENTITY,
    organization_id     UUID         NOT NULL,
    recipient           VARCHAR(254) NOT NULL,
    type                VARCHAR(64)  NOT NULL,
    payload             JSONB        NOT NULL DEFAULT '{}'::jsonb,
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts            INT          NOT NULL DEFAULT 0,
    next_attempt_at     TIMESTAMPTZ,
    provider_message_id VARCHAR(255),
    error               VARCHAR(500),
    last_attempt_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_email_outbox PRIMARY KEY (id),
    CONSTRAINT ck_email_outbox_organization_not_nil
        CHECK (organization_id <> '00000000-0000-0000-0000-000000000000'),
    CONSTRAINT ck_email_outbox_recipient
        CHECK (char_length(recipient) > 0),
    CONSTRAINT ck_email_outbox_type
        CHECK (type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_email_outbox_status
        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'RETRYING')),
    CONSTRAINT ck_email_outbox_attempts
        CHECK (attempts >= 0),
    CONSTRAINT ck_email_outbox_payload
        CHECK (jsonb_typeof(payload) = 'object' AND octet_length(payload::text) <= 4096)
);

COMMENT ON TABLE email_outbox IS 'Transactional email outbox (Spec 9.2, 12). One table serves as both the send queue and the send history via status/attempts; see b1-1/b1-2 planning notes.';
COMMENT ON COLUMN email_outbox.organization_id IS 'Tenant the email belongs to. No FK until B2 creates the organization table.';
COMMENT ON COLUMN email_outbox.type IS 'UPPER_SNAKE_CASE event code, for example EMPLOYEE_INVITED (Spec 9.1).';
COMMENT ON COLUMN email_outbox.payload IS 'Versioned structured template data {"v":1,"attributes":{}}; see EmailPayload. No secrets, no free text.';
COMMENT ON COLUMN email_outbox.status IS 'PENDING (b1-1) -> SENDING/SENT/FAILED/RETRYING are written only by the b1-2 processor job.';
COMMENT ON COLUMN email_outbox.created_at IS 'Database time (now()); the application never supplies it.';

-- Runtime role privileges: exactly what b1-1 needs, nothing b1-2 will need until it exists.
--  * SELECT is granted now so a future reader (mirroring the audit_log precedent, B0-6/4) does not
--    need its own migration just to add SELECT.
--  * INSERT is granted on exactly the four columns EmailOutboxWriter supplies: organization_id,
--    recipient, type, payload. Not id or created_at (database-generated). Not status, attempts,
--    next_attempt_at, provider_message_id, error or last_attempt_at: those all have safe defaults or
--    stay NULL at insert time, and nothing in b1-1 writes them.
--  * UPDATE is deliberately NOT granted here. Nothing in b1-1 transitions a row's status; that
--    privilege is added by the b1-2 migration alongside the processor job that actually needs it, so
--    least privilege matches what is actually shipped at every point in time, not what will eventually
--    be needed.
-- No ALTER DEFAULT PRIVILEGES: every migration grants the runtime role table by table.
REVOKE ALL ON email_outbox FROM PUBLIC;

DO $mig$
DECLARE
    runtime_role text := '${runtime_role}';
BEGIN
    EXECUTE format('GRANT SELECT ON email_outbox TO %I', runtime_role);
    EXECUTE format(
        'GRANT INSERT (organization_id, recipient, type, payload) ON email_outbox TO %I',
        runtime_role);
END
$mig$;
