package com.peoplehub.audit;

import java.net.InetAddress;
import java.util.UUID;

/**
 * One thing to append to the audit log (B0-6/9, B0-6/10). It carries only what the caller
 * legitimately knows; the actor and the correlation id come from the request or job context, and
 * the id and the time are generated by the database.
 *
 * <p>{@code organizationId} must be a real organization: never null and never the nil UUID. There
 * is deliberately no way to build an event without one, and no placeholder to use instead. Until B2
 * creates organizations no production code can supply one, so nothing calls the writer yet.
 *
 * @param organizationId the tenant the event belongs to
 * @param action UPPER_SNAKE_CASE code, at most 64 characters, for example {@code
 *     EMPLOYEE_ROLE_CHANGED}
 * @param target what the action was done to, or {@code null}
 * @param ip the client address if there was a request, else {@code null}
 * @param details structured metadata; {@link AuditDetails#none()} when there is none
 */
public record AuditEvent(
        UUID organizationId,
        String action,
        AuditTarget target,
        InetAddress ip,
        AuditDetails details) {

    private static final UUID NIL = new UUID(0L, 0L);

    public AuditEvent {
        if (organizationId == null || NIL.equals(organizationId)) {
            throw new IllegalArgumentException(
                    "An audit event needs a real organization id (not null, not the nil UUID)");
        }
        if (action == null || !AuditTarget.CODE.matcher(action).matches()) {
            throw new IllegalArgumentException(
                    "Audit action must match " + AuditTarget.CODE.pattern());
        }
        if (details == null) {
            details = AuditDetails.none();
        }
    }

    public static Builder builder(UUID organizationId, String action) {
        return new Builder(organizationId, action);
    }

    public static final class Builder {

        private final UUID organizationId;
        private final String action;
        private AuditTarget target;
        private InetAddress ip;
        private AuditDetails details = AuditDetails.none();

        private Builder(UUID organizationId, String action) {
            this.organizationId = organizationId;
            this.action = action;
        }

        public Builder target(AuditTarget target) {
            this.target = target;
            return this;
        }

        public Builder ip(InetAddress ip) {
            this.ip = ip;
            return this;
        }

        public Builder details(AuditDetails details) {
            this.details = details;
            return this;
        }

        public AuditEvent build() {
            return new AuditEvent(organizationId, action, target, ip, details);
        }
    }
}
